name: 'build and deploy production'

on:
  push:
    tags:
      - '*'

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: ${{ github.event.repository.name }}
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref }}'
    steps:
      - name: executing remoet ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: '159.223.41.181'
          username: 'root'
          password: 'Admin_1jj395qu'
          port: '22'
          script: |
            docker logout ghcr.io
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref }}
            docker rm -f ${{ env.CONTAINER_NAME }}
            docker pull ${{ env.DOCKER_IMAGE_URL }}
            docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 5512:80 ${{ env.DOCKER_IMAGE_URL }}
