name: 'build and deploy production'

on:
  push:
    tags:
      - 'v10000'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci

      - name: Run build production (create dist folder)
        run: npm run build

      - name: Upload dist folder artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist

  deploy-production-job:
    needs: build-production-job
    runs-on: ubuntu-latest
    steps:
      #   - name: Download dist folder artifacts
      #     uses: actions/download-artifact@v3
      #     with:
      #       name: dist-production
      #       path: dist

      #   - run: ls dist

      - uses: actions/checkout@v4
      - name: publish vue to github pages
        uses: SerhiiKa/VuePagesAction@1.0.4
        with:
          username: ${{ github.actor }}
          reponame: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
