name: 'CI'

on:
  push:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci

      - name: Run lint
        run: npm run lint
