name: 'CI'

on:
  push:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci

      - name: Run lint
        run: npm run lint

  unit-test-job:
    runs-on: ubuntu-latest
    needs: lint-job
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 16.x]
    steps:
      - uses: actions/checkout@v4

      - name: test on nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Run Unit Test
        run: npm run test:unit
